defaults: &defaults
  working_directory: ~/RojakAmatyaPortfolio
  docker:
    - image: circleci/node:11.6.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: npm install
        command: yarn
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: build
        command: yarn build
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
   
  deploy:
    <<: *defaults
    steps:
    - checkout
    - run:
          name: npm install
          command: yarn
    - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
    - run:
          name: firebase deploy
          command: yarn firebase deploy --token "1/j5D_yaYR-AkNdLmslBXhKjmMDA_plZUhHsT_o2z1xDQ"

workflows:
  version: 2
  build_and_deploy:
    jobs:
        - build
        - deploy:
            requires:
                - build
